import type { UserProfile, Recipient } from "@/types/database";

export const SEED_USER: Partial<UserProfile> = {
  id: "seed-user-001",
  display_name: "JT",
  personality: "Happy, fun-loving, genuine, trustworthy, loving",
  humor_style: "Witty, enjoys playful banter",
  interests: ["cooking", "gardening", "bird watching", "hiking", "travel"],
  values: ["family", "authenticity", "loyalty"],
  birthday: "06-15",
  lifestyle: "Married, active lifestyle, enjoys the outdoors and time with family",
  occupation: null,
  location: null,
  pets: null,
  children: null,
  favorite_foods: null,
  favorite_music: null,
  favorite_movies_tv: null,
  favorite_books: null,
  dislikes: null,
  communication_style: null,
  notes: null,
  partner_name: "Linda",
  partner_recipient_id: "seed-recipient-002",
  context_raw: null,
  onboarding_complete: true,
};

export const SEED_RECIPIENTS: Partial<Recipient>[] = [
  {
    id: "seed-recipient-001",
    user_id: "seed-user-001",
    name: "Zach",
    relationship_type: "nephew",
    personality_notes: "Smart, curious, a bit introverted but warms up quickly",
    interests: ["video games", "coding", "sci-fi movies", "skateboarding"],
    humor_tolerance: "Appreciates clever humor, not big on slapstick",
    tone_preference: "playful and warm",
    important_dates: [
      { label: "Birthday", date: "09-22", recurring: true },
    ],
    milestones: ["Starting college in fall"],
    context_raw: null,
    links: [{ recipient_id: "seed-recipient-003", label: "son of" }],
  },
  {
    id: "seed-recipient-002",
    user_id: "seed-user-001",
    name: "Linda",
    relationship_type: "wife",
    personality_notes: "Thoughtful, organized, warm, quietly funny",
    interests: ["reading", "yoga", "gardening", "baking", "travel"],
    humor_tolerance: "Enjoys dry humor and wordplay",
    tone_preference: "heartfelt with a touch of humor",
    important_dates: [
      { label: "Birthday", date: "03-10", recurring: true },
      { label: "Anniversary", date: "08-24", recurring: true },
    ],
    milestones: [],
    context_raw: null,
    links: [],
  },
  {
    id: "seed-recipient-003",
    user_id: "seed-user-001",
    name: "Dave",
    relationship_type: "brother",
    personality_notes: "Easygoing, loves the outdoors, dry sense of humor",
    interests: ["fishing", "woodworking", "classic cars", "grilling"],
    humor_tolerance: "Loves dry humor and good-natured ribbing",
    tone_preference: "funny and brotherly",
    important_dates: [
      { label: "Birthday", date: "11-05", recurring: true },
      { label: "Anniversary", date: "06-18", recurring: true },
    ],
    milestones: ["Turning 50 this year"],
    context_raw: null,
    links: [
      { recipient_id: "seed-recipient-004", label: "spouse" },
      { recipient_id: "seed-recipient-001", label: "parent of" },
    ],
  },
  {
    id: "seed-recipient-004",
    user_id: "seed-user-001",
    name: "Sarah",
    relationship_type: "sister-in-law",
    personality_notes: "Energetic, social, always planning something, caring",
    interests: ["interior design", "running", "book clubs", "wine tasting"],
    humor_tolerance: "Enjoys lighthearted humor and wit",
    tone_preference: "warm and appreciative",
    important_dates: [
      { label: "Birthday", date: "02-14", recurring: true },
      { label: "Anniversary", date: "06-18", recurring: true },
    ],
    milestones: [],
    context_raw: null,
    links: [
      { recipient_id: "seed-recipient-003", label: "spouse" },
      { recipient_id: "seed-recipient-001", label: "parent of" },
    ],
  },
];
