import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export async function POST(req: NextRequest) {
  if (!process.env.OPENAI_API_KEY?.trim()) {
    return NextResponse.json(
      { error: "OPENAI_API_KEY is not set. Add it in Vercel under Settings → Environment Variables." },
      { status: 500 }
    );
  }
  try {
    const body = await req.json();
    const {
      frontTitle,
      frontDescription,
      frontImagePrompt,
      occasion,
      tone,
      position,
      orientation,
      artStyle,
    }: {
      frontTitle: string;
      frontDescription: string;
      frontImagePrompt: string;
      occasion: string;
      tone: string;
      position?: string;
      orientation?: "horizontal" | "vertical" | "square";
      artStyle?: string;
    } = body;

    const shapeDesc = orientation === "horizontal"
      ? "a wide horizontal strip (roughly 5:1 ratio — very wide, very short)"
      : orientation === "vertical"
        ? "a tall vertical strip (roughly 1:5 ratio — very narrow, very tall)"
        : "a square area (used as a faded watermark behind text)";

    const positionLabel = position ?? "bottom";

    const systemPrompt = `You suggest inside-card decorations that are DERIVED FROM the front cover image. The inside decoration should look like a detail, crop, or element extracted from the front — not a completely new illustration.

FRONT OF CARD: "${frontTitle}" — ${frontDescription}
(Full front prompt: ${frontImagePrompt})
OCCASION: ${occasion}
TONE: ${tone}

PLACEMENT: ${positionLabel} of the inside card panel
FORMAT: ${shapeDesc}

The image will be GENERATED BY EDITING the front cover image — cropping, isolating, or re-composing elements from it. Your suggestions must describe which specific element(s) from the front cover to extract or feature.

RULES:
1. Each suggestion must reference a SPECIFIC visual element that exists in the front cover (e.g. "the flower cluster from the bottom-left corner", "the mountain silhouette", "the bird on the branch")
2. The element must FIT the ${shapeDesc.split("(")[0].trim()} format — wide/short elements for horizontal strips, narrow/tall for vertical strips
3. Keep it simple — one focal element or a repeating pattern from the front, not a whole new scene
4. For horizontal strips: think borders, edges, scattered elements (petals, leaves, stars), a horizon line, a decorative band
5. For vertical strips: think a single stem, a tree trunk, a flowing ribbon, a column of small repeating elements
6. Option 3 should always be "Plain crop" — just crop a section of the front image with no changes

Suggest exactly 3 options:

Respond with ONLY valid JSON:
{
  "designs": [
    {
      "title": "Short name (2-3 words)",
      "description": "What the user sees — which part of the front cover this uses.",
      "image_prompt": "Extract/crop [specific element] from the front cover image. Recompose it as a ${shapeDesc.split("(")[0].trim()} decoration. Keep the same colors, style, and artistic feel. [any small addition like 'add a subtle sparkle' or 'fade the edges to white']. No text."
    },
    { "title": "...", "description": "...", "image_prompt": "..." },
    { "title": "Plain crop", "description": "A simple cropped section from the front cover — no changes.", "image_prompt": "Crop the most visually interesting ${orientation === "horizontal" ? "horizontal band" : orientation === "vertical" ? "vertical strip" : "central area"} from this image. Keep it exactly as-is, same colors and style, just reframed to fit a ${shapeDesc.split("(")[0].trim()}. No modifications, no text." }
  ]
}`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: "Suggest 3 inside illustration concepts." },
      ],
      temperature: 0.8,
      max_tokens: 800,
    });

    const raw = completion.choices[0]?.message?.content || "";
    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("Failed to parse inside design suggestions");
    }

    const parsed = JSON.parse(jsonMatch[0]);
    return NextResponse.json(parsed);
  } catch (error: unknown) {
    console.error("Inside design suggestion error:", error);
    const message =
      error instanceof Error ? error.message : "Failed to suggest inside designs";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
