import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { checkRateLimit } from "@/lib/rate-limit";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export async function POST(req: NextRequest) {
  if (!process.env.OPENAI_API_KEY?.trim()) {
    return NextResponse.json(
      { error: "OPENAI_API_KEY is not set. Add it in Vercel under Settings → Environment Variables." },
      { status: 500 }
    );
  }
  const ip = req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "unknown";
  const rl = checkRateLimit(ip, { maxRequests: 20, windowMs: 60_000 });
  if (!rl.allowed) {
    return NextResponse.json(
      { error: "Too many requests. Please wait a moment and try again." },
      { status: 429, headers: { "Retry-After": String(Math.ceil(rl.retryAfterMs / 1000)) } }
    );
  }
  try {
    const body = await req.json();
    const {
      frontTitle,
      frontDescription,
      frontImagePrompt,
      occasion,
      tone,
      position,
      orientation,
      artStyle,
      userGuidance,
    }: {
      frontTitle: string;
      frontDescription: string;
      frontImagePrompt: string;
      occasion: string;
      tone: string;
      position?: string;
      orientation?: "horizontal" | "vertical" | "square" | "frame";
      artStyle?: string;
      userGuidance?: string;
    } = body;

    const isFrame = orientation === "frame";

    const shapeDesc = isFrame
      ? "a full-page decorative border frame (portrait orientation, roughly 2:3 ratio). The frame wraps around ALL four edges of the card, leaving the CENTER completely empty/transparent for text. Think ornamental corners connected by delicate border lines"
      : orientation === "horizontal"
        ? "a wide horizontal strip (roughly 5:1 ratio — very wide, very short)"
        : orientation === "vertical"
          ? "a tall vertical strip (roughly 1:5 ratio — very narrow, very tall)"
          : "a square area (used as a faded watermark behind text)";

    const positionLabel = position ?? "bottom";

    const systemPrompt = `You suggest inside-card decorations that are DERIVED FROM the front cover image. The inside decoration should look like a detail, crop, or element extracted from the front — not a completely new illustration.

FRONT OF CARD: "${frontTitle}" — ${frontDescription}
(Full front prompt: ${frontImagePrompt})
OCCASION: ${occasion}
TONE: ${tone}

PLACEMENT: ${positionLabel} of the inside card panel
FORMAT: ${shapeDesc}

The image will be GENERATED BY EDITING the front cover image — cropping, isolating, or re-composing elements from it. Your suggestions must describe which specific element(s) from the front cover to extract or feature.
${userGuidance ? `
CRITICAL — USER DIRECTION: The user specifically asked to focus on: "${userGuidance}".
You MUST incorporate this direction into BOTH suggestion 1 AND suggestion 2. Each should offer a different take on the user's request (e.g. different compositions, angles, or arrangements of the requested element), but BOTH must center on what the user asked for. Do NOT suggest unrelated elements.
` : ""}
RULES:
1. Each suggestion must reference a SPECIFIC visual element that exists in the front cover (e.g. "the flower cluster from the bottom-left corner", "the mountain silhouette", "the bird on the branch")${userGuidance ? `\n   — When user guidance is provided, both suggestions 1 and 2 must focus on the element(s) the user requested` : ""}
2. The element must FIT the ${shapeDesc.split("(")[0].trim()} format — wide/short elements for horizontal strips, narrow/tall for vertical strips
3. Keep it simple — one focal element or a repeating pattern from the front, not a whole new scene
4. For horizontal strips: think borders, edges, scattered elements (petals, leaves, stars), a horizon line, a decorative band
5. For vertical strips: think a single stem, a tree trunk, a flowing ribbon, a column of small repeating elements
${isFrame ? `6. For FRAMES: create a decorative border using elements from the front cover. CRITICAL LAYOUT RULES:
   - The border decoration MUST extend to the VERY EDGES of the image — touching all four sides with NO margin or padding between the decoration and the image boundary.
   - The CENTER of the image MUST be completely WHITE (pure #FFFFFF) and empty — this is where the message text goes. Leave at least 55% of the area as white space.
   - The background MUST be pure white (#FFFFFF), NOT cream, off-white, or any tinted color.
   - Think: ornamental corners connected by delicate border lines that run along the very edge of the image, scattered small elements along the borders only, or a repeating motif border.
   - The frame must be SYMMETRICAL and balanced.
7. Option 3 should be a simple, elegant frame using the most prominent motif from the front cover` : `6. Option 3 should always be "Plain crop" — just crop a section of the front image with no changes`}

Suggest exactly 3 options:

Respond with ONLY valid JSON:
{
  "designs": [
    {
      "title": "Short name (2-3 words)",
      "description": "What the user sees — which part of the front cover this uses.",
      "image_prompt": "${isFrame ? `Create a decorative border frame using [specific element] from the front cover. The border elements MUST touch all four edges of the image — no margin or padding. Arrange motifs symmetrically in all four corners connected by delicate lines along every edge. The center must be pure white (#FFFFFF) and completely empty (at least 55% white space). Background: pure white, NOT cream or off-white. Same artistic style as the front. No text.` : `Extract/crop [specific element] from the front cover image. Recompose it as a ${shapeDesc.split("(")[0].trim()} decoration. Keep the same colors, style, and artistic feel. [any small addition like 'add a subtle sparkle' or 'fade the edges to white']. No text.`}"
    },
    { "title": "...", "description": "...", "image_prompt": "..." },
    { "title": "${isFrame ? "Simple Border" : "Plain crop"}", "description": "${isFrame ? "A clean, elegant border frame using the primary motif from the front cover." : "A simple cropped section from the front cover — no changes."}", "image_prompt": "${isFrame ? `Create a symmetrical decorative border frame using the most prominent visual element from the front cover. Place ornamental motifs in all four corners connected by subtle border lines that run along the VERY EDGES of the image — no margin or padding. The center must be pure white (#FFFFFF) and completely empty — at least 55% blank white space for text. Background: pure white (#FFFFFF), NOT cream or off-white. Same artistic style as the front. No text.` : `Crop the most visually interesting ${orientation === "horizontal" ? "horizontal band" : orientation === "vertical" ? "vertical strip" : "central area"} from this image. Keep it exactly as-is, same colors and style, just reframed to fit a ${shapeDesc.split("(")[0].trim()}. No modifications, no text.`}" }
  ]
}`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: "Suggest 3 inside illustration concepts." },
      ],
      temperature: 0.8,
      max_tokens: 800,
    });

    const raw = completion.choices[0]?.message?.content || "";
    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("Failed to parse inside design suggestions");
    }

    const parsed = JSON.parse(jsonMatch[0]);
    return NextResponse.json(parsed);
  } catch (error: unknown) {
    console.error("Inside design suggestion error:", error);
    const message =
      error instanceof Error ? error.message : "Failed to suggest inside designs";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
